import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import atomics from '../styles/def.module.scss'
import Test from '../src/test';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <h1 className={atomics.a}>Welcome Ryan</h1>
        <h1 className={atomics.b}>Welcome Ryan</h1>
        <h1 className={atomics.c}>Welcome Ryan</h1>
        <Test />
      </main>
    </div>
  )
}

export default Home
